export const musicList = [
    {
      id: 1,
      title: "6 Shots ",
      artist: "NEFFEX",
      img_src: "./images/6shots.png",
      src: "./music/6Shots.mp3",
    },
    {
      id: 2,
      title: "Losing My Mind",
      artist: "NEFFEX",
      img_src: "./images/losingmymind.png",
      src: "./music/losingmymind.mp3",
    },
    {
      id: 3,
      title: "Ruthless",
      artist: "NEFFEX",
      img_src: "./images/ruthless.png",
      src: "./music/ruthless.mp3",
    },
    {
      id: 4,
      title: "What You Gonna Be",
      artist: "NEFFEX",
      img_src: "./images/whatyougonnabe.png",
      src: "./music/whatyougonnabe.mp3",
    },
    {
        id: 5,
        title: "Baddas Ravi Kumar",
        artist: "Himesh",
        img_src: "./images/image5.jpeg",
        src: "./music/BadassRaviKumar.mp3",
      },
      {
        id: 6,
        title: "Bade Miyan Chote Miyan",
        artist: "Bollywood",
        img_src: "./images/image6.jpeg",
        src: "./music/BadeMiyanChoteMiyan.mp3",
      },
      {
        id: 7,
        title: "Bhool Bhulaiyaa",
        artist: "Bollywood",
        img_src: "./images/image7.jpeg",
        src: "./music/BhoolBhulaiyaa.mp3",
      },
      {
        id: 8,
        title: "Dus Bahane",
        artist: "KK",
        img_src: "./images/image8.jpeg",
        src: "./music/DusBahane.mp3",
      },
      {
        id: 9,
        title: "Ghagra",
        artist: "Bollywood",
        img_src: "./images/image9.jpeg",
        src: "./music/Ghagra.mp3",
      },
      {
        id: 10,
        title: "Heer Aasmaani",
        artist: "B Praak",
        img_src: "./images/image10.jpeg",
        src: "./music/HeerAasmani.mp3",
      },
      {
        id: 11,
        title: "Indian Bollywood",
        artist: "Bollywood",
        img_src: "./images/image11.jpeg",
        src: "./music/indianbollywood.mp3",
      },
      {
        id: 12,
        title: "lapupu",
        artist: "Foreign",
        img_src: "./images/image12.jpeg",
        src: "./music/lapupu.mp3",
      },
      {
        id: 13,
        title: "Naina",
        artist: "Diljit Dosanjh",
        img_src: "./images/image13.jpeg",
        src: "./music/Naina.mp3",
      },
      {
        id: 14,
        title: "Sher Khul Gaye",
        artist: "Vishal Dadlani",
        img_src: "./images/image14.jpeg",
        src: "./music/SherKhulGaye.mp3",
      },
      {
        id: 15,
        title: "Tauba Tauba",
        artist: "Karan Aujla",
        img_src: "./images/image15.jpeg",
        src: "./music/TaubaTauba.mp3",
      },
      {
        id: 16,
        title: "Khel Khel Mein",
        artist: "R.D. Burman",
        img_src: "./images/image16.jpeg",
        src: "./music/KhelKhelMein.mp3",
      },
  ];